[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 15

[deploy.volumes]
data = "/data" 