[build]
builder = "nixpacks"
buildCommand = "npm install --production"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 15

[deploy.volumes]
data = "/data" 